### ISSUE TITLE
Unbound-id not checked in where: in trove

### ISSUE THREAD

**Issue by sorawee** [brownplt/pyret-lang#1127]
Say I have this code in trove:

```
fun f(x):
  y
end
```

This would result in an unbound-id as expected. However:

```
fun f(x):
  x
where:
  y is 3
end
```

does not result in any error when compiling, and since the tests are not run, this is likely to make the mistake undetected forever.

**Comment by blerner** [comment]
These would be caught by `make compiler-test`, but that appears to have bitrotted:
```
blerner@blerner-ccis-dev ~/pyret-lang> make compiler-test 
node -max-old-space-size=8192 build/phaseA/main-wrapper.js \
    --module-load-dir build/phaseA/arr/compiler/ \
    -check-all src/arr/compiler/compile.arr
module.js:442
    throw err;
    ^

Error: Cannot find module '/home/blerner/pyret-lang/build/phaseA/main-wrapper.js'
    at Function.Module._resolveFilename (module.js:440:15)
    at Function.Module._load (module.js:388:25)
    at Module.runMain (module.js:575:10)
    at run (node.js:348:7)
    at startup (node.js:140:9)
    at node.js:463:3
Makefile:301: recipe for target 'compiler-test' failed
make: *** [compiler-test] Error 1
```
@jpolitz tweaking the makefile just pushes the problem down one level, as now it can't find pyret-start.js.  Is this something you could easily tweak back into shape, or did something more systemic change?

**Comment by sorawee** [comment]
well, my concern is that it shouldn't need `make *-test` to catch that. When compiling, it would detect unbound id outside where clause, so why not include those in where to check as well?

**Comment by blerner** [comment]
Because the first thing we do in desugaring, before we can even begin to check scope, is eliminate or move check blocks to where they need to be.  If you don't compile in check mode, check blocks get erased pretty much immediately.

**Comment by jpolitz** [comment]
There are a number of weirdnesses around the timing of check block desugarings (we've had double-reported errors within check blocks in the past, for example).

It's worth considering what it would mean to leave them intact for longer, maybe until right before ANF, where order of operations starts to become an issue.
