### ISSUE TITLE
t-bot problem

### ISSUE THREAD

**Issue by sorawee** [brownplt/pyret-lang#1235]
I can't run `show-compilation` in the horizon branch because of this problem. Recently, I can't run `pyret` CLI because of this problem too. Note that I just updated my Pyret CLI via `sudo npm update -g pyret-experimental-cli`

```
$ cat test.arr
print(1)
$ pyret test.arr
Loading existing compiled modules...Error: Unknown prim type or shorthand: tbot
Error: Unknown prim type or shorthand: tbot
    at expandType (/usr/lib/node_modules/pyret-experimental-cli/build/phaseA/pyret.jarr:206864:15)
    at Object.expandType (/usr/lib/node_modules/pyret-experimental-cli/build/phaseA/pyret.jarr:206881:18)
    at /usr/lib/node_modules/pyret-experimental-cli/build/phaseA/pyret.jarr:224964:38
    at Array.map (native)
    at PBase.app (/usr/lib/node_modules/pyret-experimental-cli/build/phaseA/pyret.jarr:224962:44)
    at Object.maybeMethodCall (/usr/lib/node_modules/pyret-experimental-cli/build/phaseA/pyret.jarr:207865:22)
    at _ac1b286c61ad93f580a1166ffd2256863dd87863a935aa754e0140a43ef25f97__198 (eval at <anonymous> (/usr/lib/node_modules/pyret-experimental-cli/build/phaseA/pyret.jarr:212100:32), <anonymous>:2846:13)
    at PBase.singleton_variant [as $app_fields] (eval at <anonymous> (/usr/lib/node_modules/pyret-experimental-cli/build/phaseA/pyret.jarr:212100:32), <anonymous>:372:8)
    at PBase._ac1b286c61ad93f580a1166ffd2256863dd87863a935aa754e0140a43ef25f97__184 [as app] (eval at <anonymous> (/usr/lib/node_modules/pyret-experimental-cli/build/phaseA/pyret.jarr:212100:32), <anonymous>:2912:20)
    at PBase._ac1b286c61ad93f580a1166ffd2256863dd87863a935aa754e0140a43ef25f97__272 [as app] (eval at <anonymous> (/usr/lib/node_modules/pyret-experimental-cli/build/phaseA/pyret.jarr:212100:32), <anonymous>:3280:32)
    at foldHelp (/usr/lib/node_modules/pyret-experimental-cli/build/phaseA/pyret.jarr:211326:23)
    at foldFun (/usr/lib/node_modules/pyret-experimental-cli/build/phaseA/pyret.jarr:211336:19)
    at PBase.raw_list_map [as app] (/usr/lib/node_modules/pyret-experimental-cli/build/phaseA/pyret.jarr:211346:14)
    at Object.maybeMethodCall (/usr/lib/node_modules/pyret-experimental-cli/build/phaseA/pyret.jarr:207865:22)
    at PBase._848909f63754a080edb923188fa103a988e949ddbad56676e1dd82e254675c7b__582 [as app] (eval at <anonymous> (/usr/lib/node_modules/pyret-experimental-cli/build/phaseA/pyret.jarr:212100:32), <anonymous>:8464:14)
    at PBase._ac1b286c61ad93f580a1166ffd2256863dd87863a935aa754e0140a43ef25f97__271 [as full_meth] (eval at <anonymous> (/usr/lib/node_modules/pyret-experimental-cli/build/phaseA/pyret.jarr:212100:32), <anonymous>:3298:16)
    at Object.maybeMethodCall (/usr/lib/node_modules/pyret-experimental-cli/build/phaseA/pyret.jarr:207859:22)
    at PBase._ac1b286c61ad93f580a1166ffd2256863dd87863a935aa754e0140a43ef25f97__397 [as app] (eval at <anonymous> (/usr/lib/node_modules/pyret-experimental-cli/build/phaseA/pyret.jarr:212100:32), <anonymous>:4587:14)
    at PBase._ac1b286c61ad93f580a1166ffd2256863dd87863a935aa754e0140a43ef25f97__479 [as app] (eval at <anonymous> (/usr/lib/node_modules/pyret-experimental-cli/build/phaseA/pyret.jarr:212100:32), <anonymous>:5098:35)
    at Object.maybeMethodCall (/usr/lib/node_modules/pyret-experimental-cli/build/phaseA/pyret.jarr:207865:22)
    at PBase._3f6ba7b158335322085900c46c771bbfeda8cb5d0e09fadabaaa403d99d6f8f5__0 [as app] (eval at <anonymous> (/usr/lib/node_modules/pyret-experimental-cli/build/phaseA/pyret.jarr:212100:32), <anonymous>:506:12)
    at PBase._3f6ba7b158335322085900c46c771bbfeda8cb5d0e09fadabaaa403d99d6f8f5__90 [as app] (eval at <anonymous> (/usr/lib/node_modules/pyret-experimental-cli/build/phaseA/pyret.jarr:212100:32), <anonymous>:1041:27)
    at thisRuntime.run.sync (/usr/lib/node_modules/pyret-experimental-cli/build/phaseA/pyret.jarr:210733:24)
    at ActivationRecord.fun (/usr/lib/node_modules/pyret-experimental-cli/build/phaseA/pyret.jarr:210332:18)
    at iter (/usr/lib/node_modules/pyret-experimental-cli/build/phaseA/pyret.jarr:210450:28)
    at Object.run (/usr/lib/node_modules/pyret-experimental-cli/build/phaseA/pyret.jarr:210549:7)
    at Cont.resumer (/usr/lib/node_modules/pyret-experimental-cli/build/phaseA/pyret.jarr:210732:21)
    at iter (/usr/lib/node_modules/pyret-experimental-cli/build/phaseA/pyret.jarr:210476:41)
    at Object.run (/usr/lib/node_modules/pyret-experimental-cli/build/phaseA/pyret.jarr:210549:7)
    at Object.runThunk (/usr/lib/node_modules/pyret-experimental-cli/build/phaseA/pyret.jarr:210711:26)
    at tryQueue (/usr/lib/node_modules/pyret-experimental-cli/build/phaseA/pyret.jarr:236090:23)
    at WebSocket.<anonymous> (/usr/lib/node_modules/pyret-experimental-cli/build/phaseA/pyret.jarr:236133:15)
    at emitOne (events.js:96:13)
    at WebSocket.emit (events.js:188:7)
    at Receiver._receiver.onmessage (/usr/lib/node_modules/pyret-experimental-cli/node_modules/ws/lib/WebSocket.js:143:47)
    at Receiver.dataMessage (/usr/lib/node_modules/pyret-experimental-cli/node_modules/ws/lib/Receiver.js:389:14)
    at Receiver.getData (/usr/lib/node_modules/pyret-experimental-cli/node_modules/ws/lib/Receiver.js:330:12)
    at Receiver.startLoop (/usr/lib/node_modules/pyret-experimental-cli/node_modules/ws/lib/Receiver.js:165:16)
    at Receiver.add (/usr/lib/node_modules/pyret-experimental-cli/node_modules/ws/lib/Receiver.js:139:10)
    at Socket._ultron.on (/usr/lib/node_modules/pyret-experimental-cli/node_modules/ws/lib/WebSocket.js:139:22)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at Pipe.onread (net.js:547:20)
```

**Comment by jpolitz** [comment]
It seems like there's likely a bad stale compiled file somewhere. Can you try removing ".pyret" in the directory you're in?

I can't reproduce this with the `pyret` command myself.

**Comment by sorawee** [comment]
Unfortunately, still doesn't work.

**Comment by jpolitz** [comment]
Have you been running `pyret.js` from a local checkout, or used `npm link` on a local checkout, as well? I've had `npm` pretty confused about paths before when I've mixed and matched.

**Comment by sorawee** [comment]
I `sudo npm -g i pyret-experimental-cli` a couple of weeks ago, and `sudo npm update -g pyret-experimental-cli` today and that's all. Never use `npm link` and don't know how to use it.

`which pyret` outputs `/usr/bin/pyret`, so I don't think it's the development version (if that's what you meant by local checkout).

**Comment by jpolitz** [comment]
Maybe try `sudo npm -g i pyret-experimental-cli` again (not update)?

I've had issues sometimes with update not updating (potentially related to https://github.com/npm/npm/issues/11534).

**Comment by sorawee** [comment]
Even uninstalling it and installing again doesn't help...

**Comment by jpolitz** [comment]
I really feel that it must be stale state somewhere in the filesystem,
likely quite local to the file you are running.

Is it the case that you made a new directory, put a Pyret file there, ran
`pyret` from within that directory, and got the same error?

**Comment by sorawee** [comment]
Since I reported, I did two things:

1. Restart my computer
2. `git checkout <another-branch>` on the directory that has the Pyret file

One of these (or both) fixes the problem.
