### ISSUE TITLE
shared-gdrive is not functional in patch-experiment.herokuapp.com

### ISSUE THREAD

**Issue by sorawee** [brownplt/pyret-lang#420]
I am reported that:

    There was an error while reporting the error:
    "TypeError: Cannot read property 'dict' of undefined
    at Object.hasField (https://d251z2akfyabv3.cloudfront.net/v0.5r763-test/pyret.js:5823:45)
    at Object.hoverLink (https://patch-experiment.herokuapp.com/js/output-ui.js:196:17)
    at singleHover (https://patch-experiment.herokuapp.com/js/error-ui.js:46:18)
    at https://patch-experiment.herokuapp.com/js/error-ui.js:353:13
    at https://patch-experiment.herokuapp.com/js/error-ui.js:264:13
    at Object.safeCall (https://d251z2akfyabv3.cloudfront.net/v0.5r763-test/pyret.js:6762:20)
    at getDomValue (https://patch-experiment.herokuapp.com/js/error-ui.js:261:19)
    at drawGenericTypeMismatch (https://patch-experiment.herokuapp.com/js/error-ui.js:342:11)
    at PBase.$generic_DASH_type_DASH_mismatch_getfieldsref671672 [as $app_fields] (https://d251z2akfyabv3.cloudfront.net/v0.5r763-test/pyret.js:24858:8)
    at PBase.f [as full_meth] (https://d251z2akfyabv3.cloudfront.net/v0.5r763-test/pyret.js:5112:25)"

**Comment by sorawee** [comment]
More information:

In patch-experiment.herokuapp.com, I can't import code via shared-gdrive from neither CPO nor patch-experiment.herokuapp.com.

The shown error is 

    Expected to get a Boolean as an argument, but got this instead:
    nothing
    at

Going to the console, I get the message I originally reported (TypeError: Cannot read property 'dict' of undefined)

**Comment by jpolitz** [comment]
Fixed by cbd401ea1aeec6bfcdd43133f416cf020fde9d28

**Comment by sorawee** [comment]
It's not bootstrapped yet? I still got the same error.

**Comment by jpolitz** [comment]
Did you refresh?  I pushed out the new version and it works for me.

**Comment by sorawee** [comment]
That's why! Thank you :)
