### ISSUE TITLE
Cannot name a method `_match`

### ISSUE THREAD

**Issue by justinpombrio** [brownplt/pyret-lang#487]
Calling a data method `_match`:

    data Foo:
      | foo(x)
        with: _match(self): self.x end
    end

    check:
      foo(3)._match() is 3
    end

results in a JS error:

    TypeError: Cannot read property 'dict' of undefined TypeError: Cannot read property 'dict' of undefined at hasField (https://d251z2akfyabv3.cloudfront.net/v0.5r852/pyret.js:5892:45) at PBase.f [as full_meth] (https://d251z2akfyabv3.cloudfront.net/v0.5r852/pyret.js:5180:14) at PBase.$temp_lam11581159 [as app] (eval at <anonymous> (https://d251z2akfyabv3.cloudfront.net/v0.5r852/pyret.js:63197:9), <anonymous>:472:29) at thisRuntime.run.sync (https://d251z2akfyabv3.cloudfront.net/v0.5r852/pyret.js:7249:26) at ActivationRecord.fun (https://d251z2akfyabv3.cloudfront.net/v0.5r852/pyret.js:6902:16) at iter (https://d251z2akfyabv3.cloudfront.net/v0.5r852/pyret.js:7013:26) at Object.run (https://d251z2akfyabv3.cloudfront.net/v0.5r852/pyret.js:7075:5) at Cont.resumer (https://d251z2akfyabv3.cloudfront.net/v0.5r852/pyret.js:7248:21) at iter (https://d251z2akfyabv3.cloudfront.net/v0.5r852/pyret.js:7040:33) at Object.run (https://d251z2akfyabv3.cloudfront.net/v0.5r852/pyret.js:7075:5)

**Comment by jpolitz** [comment]
Mmph.  That's actually just the internal implementation of `_match` not checking arguments correctly.  Thanks.  We should decide what to do with this, because calling `_match` directly is pseudo-supported but not strictly necessary.  The internal implementation is used for cases, but doesn't need to be.

**Comment by jpolitz** [comment]
Smallest repro is

```
empty._match()
```

**Comment by blerner** [comment]
That's pretty small :)  Looks like the problem is in `makeMatch`, in runtime-anf.  Neither piece of  `makeMatch` does an arity check, but they probably should.  (Since the compilation of `cases` no longer calls `_match`, we're actually free to modify this method however we want.  We should modify it by adding the standard preamble we add to all methods.)

**Comment by jpolitz** [comment]
Good point about the update of `cases`.  Now the compiler is the only place we use this.  We could rid ourselves entirely of it with some boilerplate added to the compiler, which is probably the right thing to do.  If we want to provide something programmatic like this, it's not necessarily best to have it as a magic method.

**Comment by blerner** [comment]
True.  Perhaps we can expose it as a js-native, compiler-only library `doDoubleDispatch(datum, visitor, else-thunk)` or something?  I mean, that's all we're using it for...though it is nice that we happen to have support for visitors "built in" to Pyret ;-)

**Comment by jpolitz** [comment]
Yeah, it does save a fair amount of code.

In the spirit of avoiding dark corners, though, I'm inclined to just take it out entirely.  The whole idea of built-in visitors is worth designing rather than having Joe's random desugaring get standardized.

**Comment by blerner** [comment]
This has gotten worse; it's now an "internal errors prevented ..." message.  `_match` really needs to go.
